image: node:21.7.1-slim
variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - lint
  - test
  - build
  - pages

default:
  before_script:
    # Install bash and make
    - (apt update && apt-get install make)
    # Install npm packages
    - npm install
  cache:
    - key:
        files:
          - package.lock
          - package-lock.json
        prefix: $CI_COMMIT_REF_SLUG
      paths:
        # Cache node_modules
        - node_modules/
        - .npm/
        # Cache Cypress binary
        - cache/Cypress

include:
  # Documentation
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/docs.gitlab-ci.yml'
  # Badges from CI metrics
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/finaliser.gitlab-ci.yml'

js-lint:
  stage: lint
  script:
    - make js-format
    - make js-lint
  after_script:
    - mkdir -p build/reports
    - |
      if [[ -f linting.xml ]]; then
        mv linting.xml build/reports/linting.xml;
      fi;
  artifacts:
    paths:
      - build/
    expire_in: 2 days

js-test:
  stage: test
  image: cypress/browsers:node-20.12.2-chrome-124.0.6367.60-1-ff-125.0.1-edge-124.0.2478.51-1
  before_script:
    - (apt update && apt-get install make)
    - npm ci
    - npx cypress cache path
    - npx cypress cache list
  script:
    - make js-test
  artifacts:
    paths:
      - build/
    expire_in: 2 days

js-build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 2 days

create-ci-metrics:
  # Override default before_script in post stage
  before_script:
    - []
